# Project Variables
PROJECT_NAME ?= SolarCoffee
ORG_NAME ?= SolarCoffee
REPO_NAME ?= SolarCoffee

.PHONY: migrations db

migrations:
cd ./SolatCoffee.Data && dotnet ef --startup-project ../SolarCoffee.Web/ migrations add $(mname) && cd ..

db:
cd ./SolatCoffee.Data && dotnet ef --startup-project ../SolarCoffee.Web/ database update && cd ..